sudo: required
language: node_js
node_js:
    - "6"
install:
    - apt-get install -y bluetooth bluez libbluetooth-dev libudev-dev
    - npm install
test:
    - npm test
after_success: 
    - npm run coveralls