sudo: required
language: node_js
node_js:
    - "6"
install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq bluetooth bluez libbluetooth-dev libudev-dev
    - npm install
test:
    - npm test
after_success: 
    - npm run coveralls