sudo: required
language: node_js
node_js:
    - "6"
install:
    - sudo apt-get install -qq gcc-5 g++-5
    - sudo apt-get install -qq bluetooth bluez libbluetooth-dev libudev-dev
    - npm install -g npm node-gyp
    - npm install
test:
    - npm test
after_success: 
    - npm run coveralls