sudo: required
language: node_js
node_js:
    - "6"
install:
    - curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -
    - sudo apt-get install -qq nodejs build-essential
    - sudo apt-get install -qq make bluetooth bluez libbluetooth-dev libudev-dev
    - npm install -g npm node-gyp
    - npm install
test:
    - npm test
after_success: 
    - npm run coveralls